Add flag to skip bundling extension safe builds in frameworks for DDM (#168955)
This attempts to resolve an error like:

```
Cannot find extension safe iOS arm64 Framework at /Volumes/Work/s/w/ir/cache/builder/engine/src/out/ci/ios_debug_ddm_extension_safe/Flutter.framework
ERROR: binaries listed in entitlements.txt, without_entitlements.txt, andunsigned_binaries.txt do not match the set of binaries in the files to be zipped
Binaries found in files to be zipped:
    Flutter.xcframework/ios-arm64/Flutter.framework/Flutter
    Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter
    gen_snapshot_arm64
Binaries listed in entitlements.txt, without_entitlements.txt, unsigned_binaries.txt but NOT FOUND:
    extension_safe/Flutter.xcframework/ios-arm64/Flutter.framework/Flutter
    extension_safe/Flutter.xcframework/ios-arm64_x86_64-simulator/Flutter.framework/Flutter
```

This was coming from
[create_ios_framework.py](https://github.com/flutter/flutter/blob/a99a3e5c286b8333a53d6368f41345b28b2b50ac/engine/src/flutter/sky/tools/create_ios_framework.py)
which assumes that extension safe frameworks are being built.

I verified that this works using the following:

```sh
et build --config ci/ios_debug_sim_ddm && \
    et build --config ci/ios_debug_sim_arm64_ddm && \
    et build --config ci/ios_debug_ddm && \
    et build --config ci/ios_release_ddm

python3 \
  engine/src/flutter/sky/tools/create_ios_framework.py \
  --dst \
  out/debug_ddm \
  --arm64-out-dir \
  out/ci/ios_debug_ddm \
  --simulator-x64-out-dir \
  out/ci/ios_debug_sim_ddm \
  --simulator-arm64-out-dir \
  out/ci/ios_debug_sim_arm64_ddm \
  --no-extension-safe-frameworks
  ```