Filter None out of module_paths for android build_utils.py (#516)
The abspath of Python3.8 can't process None as input parameter, and it
will throw the following exception if it is None:

Traceback (most recent call last):
  File "../../build/android/gyp/javac.py", line 345, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../build/android/gyp/javac.py", line 338, in main
    input_files + build_utils.GetPythonDependencies())
  File "/home/dev/workspace/flutter/src/build/android/gyp/util/build_utils.py", line 322, in GetPythonDependencies
    non_system_module_paths = [
  File "/home/dev/workspace/flutter/src/build/android/gyp/util/build_utils.py", line 322, in <listcomp>
    non_system_module_paths = [
  File "/usr/lib/python3.8/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

There are two related Python issues:
https://bugs.python.org/issue36777
https://bugs.python.org/issue33399

Signed-off-by: utzcoz <utzcoz@outlook.com>