Revert "[tools][fuchsia] Do not tar debug symbol CIPD uploads (#17275)" (flutter/engine#17501)
Breaks CIPD package creation on Fuchsia.

Example error message:

    Directory: /b/s/w/ir/k/recipe_cleanup/tmp9x3dHw is not empty, deleting it.
    Traceback (most recent call last):
      File "/b/s/w/ir/cache/builder/src/flutter/tools/fuchsia/merge_and_upload_debug_symbols.py", line 140, in <module>
        sys.exit(main())
      File "/b/s/w/ir/cache/builder/src/flutter/tools/fuchsia/merge_and_upload_debug_symbols.py", line 131, in main
        HardlinkContents(symbol_dir, out_dir)
      File "/b/s/w/ir/cache/builder/src/flutter/tools/fuchsia/merge_and_upload_debug_symbols.py", line 83, in HardlinkContents
        os.makedirs(dest_dir)
      File "/b/s/w/ir/cache/vpython/9f7888/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 17] File exists: '/b/s/w/ir/k/recipe_cleanup/tmp9x3dHw/.'

This reverts commit bcc617baecc455835c73b424095531383d09462c.