[CP-stable]Add xcresulttool --legacy flag for deprecated usage (#153117)
### Issue Link:
https://github.com/flutter/flutter/issues/152989

### Changelog Description:
On Xcode 16 beta, compilation errors are not displayed in the output of `flutter run`.

### Impact Description:

If there are compilation errors `flutter build ios`/`run` will fail, but displays the last x lines out the Xcode output instead of a nicely formatted description of the error.

### Workaround:
Use Xcode 15.

### Risk:
What is the risk level of this cherry-pick?

### Test Coverage:
Are you confident that your fix is well-tested by automated tests?

### Validation Steps:
Run the following steps with both Xcode 15 and Xcode 16 installed (should behave the same):
```
$ flutter create test_create
$ cd test_create
$ open ios/Runner/AppDelegate.swift
```
Add code that would cause a compilation issue:
```swift
import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    var i = 1 + @""
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
```
$ flutter build ios
```

Output should be:
```
Failed to build iOS app
Swift Compiler Error (Xcode): String literals in Swift are not preceded by an '@' sign
/Users/m/Projects/test_create/ios/Runner/AppDelegate.swift:9:16

Swift Compiler Error (Xcode): Binary operator '+' cannot be applied to operands of type 'Int' and 'String'
/Users/m/Projects/test_create/ios/Runner/AppDelegate.swift:9:14

Encountered error while building for device.
```